baseURL = 'https://seanfeldman.com/'
languageCode = 'en-us'
title = 'Sean Feldman Blog'
theme = 'github.com/HEIGE-PCloud/DoIt'

[permalinks]
posts = "/posts/:slug"

[services]
    [service.Disqus]
        shortname = 'sean-feldman-blog'

[privacy]
    [privacy.disqus]
        disable = false

# DoIt theme configuration: enable Disqus comments
[params]
	[params.page]
		[params.page.comment]
			enable = true
			[params.page.comment.disqus]
				enable = true
				shortname = "sean-feldman-blog"
