name: Build and Deploy Statiq Web

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write
  actions: read
  pages: write
  id-token: write
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore src/Blog/Blog.csproj

      - name: Build and generate site
        run: dotnet run --project ./src/Blog -- --output ./src/Blog/output

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/Blog/output
          keep_files: false
          force_orphan: true

      - name: Deploy PR preview to GitHub Pages
        if: github.event_name == 'pull_request'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/Blog/output
          destination_dir: pr-${{ github.event.pull_request.number }}
          keep_files: true
          publish_branch: gh-pages #validation
          
      - name: List output contents
        run: ls -la ./src/Blog/output

      - name: Comment with Preview URL
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const repo = context.repo.repo;
            const owner = context.repo.owner;
            const previewUrl = `https://${owner}.github.io/${repo}/pr-${prNumber}/`;
            github.rest.issues.createComment({
              issue_number: prNumber,
              owner,
              repo,
              body: `🚀 Preview your changes here: [${previewUrl}](${previewUrl})`
            });